#!/usr/bin/env bash

# Exit if there are no refs/commits in the repo yet
HEADS_DIR=$(realpath -e $(git rev-parse --git-path refs/heads))
if [[ ! -d "$HEADS_DIR" ]] || [[ -z `ls -A "$HEADS_DIR"` ]]; then
  exit 0;
fi

FILE=$1
MESSAGE=$(cat $FILE)
TICKET=[$(git rev-parse --abbrev-ref HEAD \
  | grep -Eo '^(\w+/)?(\w+[-_])?[0-9]+' \
  | grep -Eo '(\w+[-])?[0-9]+' \
  | tr "[:lower:]" "[:upper:]")]

# Exit if ticket number is empty or already in the message
if [[ $TICKET == "[]" || "$MESSAGE" == "$TICKET"* ]]; then
  exit 0;
fi

echo "$TICKET $MESSAGE" > $FILE
